services:
  - type: web
    name: python-cgi-demo
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
